<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Resources\icon_gray.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\icon_gray.ico" />
    <EmbeddedResource Include="Resources\icon_green.ico" />
    <EmbeddedResource Include="Resources\icon_red.ico" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260627" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.13.0.20260627" />
    <PackageReference Include="System.Management" Version="10.0.12" />
    <PackageReference Include="Telegram.Bot" Version="22.10.3.2" />
  </ItemGroup>

</Project>